"use client";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
//import "./sarahstyle.css";
//import "./nikitha.css";
//import { useEffect } from "react";
import { Abril_Fatface } from "next/font/google";
import Link from "next/link";
import Script from "next/script";
import "../app/styles/sarahstyle.css";
import { useEffect } from "react";
import { UserProvider } from "./context/usercontext";
import { useUser } from "./context/usercontext";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const abrilFatface = Abril_Fatface({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-abril-fatface", // Optional: for CSS variable usage
});

export function Heading() {
  const { user, setUser } = useUser();
  useEffect(() => {
    // Always read from localStorage on mount
    const storedName = localStorage.getItem("CustFirstName");
    if (storedName && !user) {
      setUser(storedName);
    }
  }, []);

  return (
    <header className={`bg-body-tertiary py-4  ${abrilFatface.className}`}>
      <div className="container ">
        <div className="row ">
          {/* Logo and tagline */}
          <div className="col-md-4  pt-3">
            <Link href="/" className="text-decoration-none">
              <h4 className="text-uppercase text-secondary text-decoration-none">
                World Travel
              </h4>
            </Link>
          </div>

          {/* Quick links */}
          <div className="col-md-4  pt-3 ">
            <ul className="list-unstyled flex flex-row ">
              <li>
                <Link
                  href="/vacation-package"
                  className="text-secondary pr-6 text-decoration-none"
                >
                  Vacation Package
                </Link>
              </li>
              <li>
                <Link
                  href="/about"
                  className="text-secondary pr-6 text-decoration-none"
                >
                  About Us
                </Link>
              </li>
              <li>
                <Link
                  href="/contact"
                  className="text-secondary pr-6 text-decoration-none"
                >
                  Contact
                </Link>
              </li>
              {/* <li>
                <Link
                  href="/customer"
                  className="text-secondary text-decoration-none"
                >
                  Register
                </Link>
              </li> */}
            </ul>
          </div>
          {/* Greeting */}
          <div className="col-md-4 pt-3 text-end">
            {user ? (
              <>
                <span className="text-secondary small me-3">
                  Welcome, {user}!
                </span>
                <button
                  className="btn btn-sm btn-outline-secondary"
                  onClick={() => {
                    localStorage.removeItem("CustFirstName");
                    // window.location.reload();  refresh to update UI
                    setUser(""); // instantly update UI
                  }}
                >
                  Logout
                </button>
              </>
            ) : (
              <Link href="/login" className="btn btn-sm btn-outline-primary">
                Login
              </Link>
            )}
          </div>

          {/* Social or contact */}
        </div>
      </div>
    </header>
  );
}

export function Footer() {
  return (
    <footer className={`bg-body-tertiary py-4 mt-5 ${abrilFatface.className}`}>
      <div className="container">
        <div className="row">
          {/* Logo and tagline */}
          <div className="col-md-4 mb-3">
            <h4 className="text-uppercase text-secondary">World Travel</h4>
            <p className="small text-secondary">Explore. Dream. Discover.</p>
          </div>

          {/* Quick links */}
          <div className="col-md-4 mb-3 text-secondary">
            <h5>Quick Links</h5>
            <ul className="list-unstyled">
              <li>
                <Link
                  href="/vacation-package"
                  className="text-secondary text-decoration-none"
                >
                  Vacation Package
                </Link>
              </li>
              <li>
                <Link
                  href="/about"
                  className="text-secondary pr-6 text-decoration-none"
                >
                  About Us
                </Link>
              </li>
              <li>
                <Link
                  href="/contact"
                  className="text-secondary pr-6 text-decoration-none"
                >
                  Contact
                </Link>
              </li>

              <li>
                <Link
                  href="/customer"
                  className="text-secondary text-decoration-none"
                >
                  Register
                </Link>
              </li>
            </ul>
          </div>

          {/* Social or contact */}
          <div className="col-md-4 mb-3">
            <h5 className="text-secondary">Connect</h5>
            <p className="small text-secondary">Email: info@worldtravel.com</p>
            <p className="small text-secondary">Phone: +1 (800) 555-TRVL</p>
          </div>
        </div>

        <hr className="border-dark" />
        <div className="text-center small text-secondary">
          &copy; {new Date().getFullYear()} World Travel. All rights reserved.
        </div>
      </div>
    </footer>
  );
}

export default function RootLayout({ children }) {
  // useEffect(() => {
  // Dynamically import Bootstrap's JavaScript bundle
  //   import("bootstrap/dist/js/bootstrap.bundle.min.js");
  // }, []);
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Heading />
          <main>{children}</main>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
